{{- if and (not .Values.config.garage.existingSecret.name) .Values.config.garage.admin_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage-ui.fullname" . }}-admin-token
  labels:
    {{- include "garage-ui.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.config.garage.admin_token | b64enc | quote }}
{{- end }}
