apiVersion: v1
entries:
  garage-ui:
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-19T19:29:09.7730355+01:00"
    description: A Helm chart for Garage UI - Web interface for Garage S3 object storage
    digest: 3aaae7bc0be5de3fd58597a78732e903bb05bd15a00365a7d4cc5277a7363593
    home: https://github.com/Noooste/garage-ui
    keywords:
    - garage
    - s3
    - object-storage
    - ui
    - dashboard
    - web-ui
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: Noooste
    name: garage-ui
    sources:
    - https://github.com/Noooste/garage-ui
    type: application
    urls:
    - https://noooste.github.io/garage-ui/garage-ui-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-19T19:29:09.771875+01:00"
